title: Matt Grant
subtitle: A heap of information about a goofy developer
description: >- # this means to ignore newlines until "baseurl:"
  The majority of the information on this personal website will be about my coding knowledge;
  however, it also contains some spicy content that encapsulates some of my other interests.

url: "https://mattgrantumich.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    #- text: Blog
    #  url: /blog
    #- text: Gallery
    #  url: /gallery
    #- text: Shop
    #  url : /shop
    - text: Contact Me
      url : /contact
    - text: Styleguide
      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit these details

author_logo: profile.png
author: Matt Grant
author_bio: Hi, welcome to my site I built using devlopr-jekyll!
author_email: "mattgra@umich.edu"
author_location: Ann Arbor, MI
typewrite-text: Sure do like pumpkins, Cotton

author_work_experiences:
  - company_name: S-Docs
    company_logo: s-docs_logo.png
    company_url: https://sdocs.com
    designation: Software Engineer
    time_period_at_company: Summer 2019 - Present
    description:
      Working with the Full Stack of Salesforce, 
      with a strong focus on Product Quality
    visibility: true
  - company_name: Target
    company_logo: target_logo.png
    company_url: https://target.com
    designation: Software Engineer Intern
    time_period_at_company: Summer 2018
    description:
      Took on various projects within the Clearance Pricing
      team, with a focus on Java development within the
      Spring Framework
    visibility: true
  - company_name: U-M Information and Technology Services
    company_logo: michigan-its_logo.png
    company_url: https://its.umich.edu/
    designation: Software Engineer Intern
    time_period_at_company: Summer 2017
    description:
      Developed a new Automated Testing system within
      the team's .NET codebase, as well as updated old
      HTML pages to have a new, slicker look.
    visibility: true

author_education_details:
  - college_logo: michigan-engineering_logo.jpg
    college_name: University of Michigan
    college_url: https://umich.edu
    college_degree: Computer Science Engineering (Minor in Business & Music)
    description: Bachelor of Science
    visibility: true

author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Projects to Come!
    project_description: A Platform to place personal projects.
    project_url: https://google.com
    visibility: true




# social links
twitter_username: 410TubaV2
github_username:  MattGrantUmich
linkedin_username: matthew-grant-ab5006112

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: mattgrantumich

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: maylowlo

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
# collections:
# - products

# Gallery
# defaults:
#   -
#     scope:
#       path: "gallery"
#     values:
#       permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
