title: Matt Grant
subtitle: Software Engineer
description: >- # this means to ignore newlines until "baseurl:"
  The majority of the information on this personal website will be about my coding knowledge;
  however, it also contains some spicy content that encapsulates some of my other interests.

url: "https://mattgrantumich.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# NOTE: Uncomment any of these tabs if you need to see the related content for an example
# IF YOU ARE GOING TO DELETE A TAB, make sure all related content is also removed for clean code purposes
urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Vinyl
      url: /vinyl
    - text: My Spotify
      url: /my-spotify
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: profile.png
author: Matt Grant
author_bio: >-
  Hello World! My name is Matt Grant, and I am a Software Engineer based in Ann Arbor.
  I have been coding since my high school days, and it has been a passion of mine ever
  since. Outside of the beep boops, I have an adoration for music in general. I play the
  tuba, am picking up the piano, and am  definitely a high-quality melodica player
  (this one is just not true). To add, I am a bit of an audiophile (see Vinyl tab).
  Feel free to take a look around my personal website, I hope you are able to find
  some 🌶️ spicy 🌶️, quality content.


  

author_email: "mattgrantumich@gmail.com"
author_location: Ann Arbor, MI
typewrite-text: Coding, Music, and an undying love for the Chicago Bears all bundled into one goofy guy

author_work_experiences:
  - company_name: S-Docs
    company_logo: s-docs_logo.png
    company_url: https://sdocs.com
    designation: Software Engineer
    time_period_at_company: Summer 2019 - Present
    description: >
      Developing on the Full Stack of Salesforce, 
      with a current focus on Product Quality.
      Producing stronger code, increasing algorithmic
      efficiency, and working with a variety of Salesforce tools
      to continuously improve the App Exchange packages: S-Docs & S-Sign.
    visibility: true
  - company_name: Target
    company_logo: target_logo.png
    company_url: https://target.com
    designation: Software Engineer Intern
    time_period_at_company: Summer 2018
    description:
      Took on various projects within the Clearance Pricing
      team, with a focus on Java development within the
      Spring Framework.
    visibility: true
  - company_name: U-M Information and Technology Services
    company_logo: michigan-its_logo.png
    company_url: https://its.umich.edu/
    designation: Software Engineer Intern
    time_period_at_company: Summer 2017
    description:
      Developed a new Automated Testing system within
      the team's .NET codebase, as well as updated old
      HTML pages to have a new, slicker look.
    visibility: true

author_education_details:
  - college_logo: michigan-engineering_logo.jpg
    college_name: University of Michigan
    college_url: https://umich.edu
    college_degree: Computer Science Engineering
    college_graduation_month: May 2019
    college_minors: Minor in Business & Music
    description: Bachelor of Science
    visibility: true

author_project_details:
  - project_thumbnail: goldify_logo.png
    project_title: Goldify
    project_url: https://github.com/Goldify/Goldify
    project_description: >-
      A Spotify API based React application which
      helps you to build a golden playlist of your top songs!
      This project maintains 100% test coverage, uses
      Material UI standards, and is built as a responsive
      application.
    visibility: true
  - project_thumbnail: profile.png
    project_title: My Personal Website
    project_url: https://github.com/MattGrantUMich/MattGrantUmich.github.io
    project_description: >-
      This very webiste has seen many
      additions over the past few months and will continue to be
      developed on. My goal is of course to build an easy-to-navigate
      source for the minutia of my life. I think it's not bad so far!
    visibility: false




# social links
# I should probably tweet a little first...... twitter_username: 410TubaV2
github_username:  MattGrantUmich
linkedin_username: mattgrantumich
twitter_username: MattGrantUmich
spotify_username: mgrant35
soundcloud_username: bill-burns-the-first

# wakatime username (coding activity)
wakatime_username: mattgrantumich

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_recent_articles_section: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
