# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Updates the JSON for Matt Grant's Discogs Vinyl Wantlist
      - name: Update Discogs Wantlist
        run: curl https://api.discogs.com/users/mattgra/wants -o _data/vinyl/wantlist.json

      # Updates the JSON for Matt Grant's Discogs Vinyl Collection
      - name: Update Discogs Collection
        run: curl https://api.discogs.com/users/mattgra/collection/folders/0/releases -o _data/vinyl/collection.json
